executor: CeleryKubernetesExecutor

# Redis configuration
redis:
  password: my_redis_password
  resources:
    requests:
      cpu: "250m"
      memory: "2Gi"
    limits:
      cpu: "500m"
      memory: "4Gi"

# DAGs configuration - disable Git-sync and use S3 sync with Goofys
dags:
  gitSync:
    enabled: false

# Define DAGs volume and mount points for all components
extraVolumes:
  - name: dags
    emptyDir: {}

scheduler:
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
  resources:
    requests:
      cpu: "250m"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "4Gi"
  securityContext:
    runAsUser: 50000
    runAsGroup: 50000
    fsGroup: 50000

webserver:
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
  resources:
    requests:
      cpu: "250m"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "4Gi"
  securityContext:
    runAsUser: 50000
    runAsGroup: 50000
    fsGroup: 50000
  service:
    type: NodePort  # Changed from LoadBalancer to NodePort for Minikube
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@example.com
    firstName: admin
    lastName: user
    password: admin

workers:
  replicas: 1
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
  resources:
    requests:
      cpu: "250m"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "4Gi"
  securityContext:
    runAsUser: 50000
    runAsGroup: 50000
    fsGroup: 50000

triggerer:
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
  resources:
    requests:
      cpu: "250m"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "4Gi"
  securityContext:
    runAsUser: 50000
    runAsGroup: 50000
    fsGroup: 50000

dagProcessor:
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
  securityContext:
    runAsUser: 50000
    runAsGroup: 50000
    fsGroup: 50000

# Custom Celery configurations
config:
  celery:
    worker_concurrency: 8
    worker_prefetch_multiplier: 1
    task_acks_late: true
    task_queue_max_priority: 10
    broker_transport_options: '{"visibility_timeout": 21600}'

# Define global sidecar containers
extraContainers:
  - name: goofys
    image: kishoreel/goofys-image:latest
    command:
      - /bin/sh
      - -c
      - |
        goofys --debug_s3 airflow-dags-stage /opt/airflow/dags -o allow_other -o url=https://s3.amazonaws.com
    securityContext:
      runAsUser: 0
      privileged: true
    volumeMounts:
      - name: dags
        mountPath: /opt/airflow/dags
    env:
      - name: AWS_REGION
        value: "ap-south-1"
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: access-key-id
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: secret-access-key


# Pod Security Context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 50000
  runAsGroup: 50000
  fsGroup: 50000

volumes:
  - name: dags
    emptyDir: {}

# Add ingress configuration
ingress:
  enabled: true
  web:
    path: "/"
  host: "airflow.local"
