# Airflow configuration
executor: CeleryKubernetesExecutor

# Redis configuration
redis:
  enabled: true
  password: my_redis_password
  resources:
    requests:
      cpu: "250m"
      memory: "2Gi"
    limits:
      cpu: "500m"
      memory: "4Gi"

# DAGs configuration - disable Git-sync and use S3 sync with Rclone
dags:
  gitSync:
    enabled: false

# Common volume definitions
volumes:
  - name: dags
    emptyDir: {}
  - name: rclone-config
    configMap:
      name: rclone-config
  - name: log-volume
    emptyDir: {}

# Worker configuration
worker:
  enabled: true
  replicas: 1
  extraVolumes:
    - name: rclone-config
      configMap:
        name: rclone-config
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
    - name: rclone-config
      mountPath: /config
    - name: log-volume
      mountPath: /var/log
  extraContainers:
    - name: rclone-sync
      image: kishoreel/rclone2-image:latest
      command:
        - /bin/bash
        - -c
        - |
          echo "Mount point for rclone config: /config/rclone.conf"
          while true; do
            echo "Running rclone sync..."
            rclone sync s3:airflow-dags-stage /opt/airflow/dags --config /config/rclone.conf --use-server-modtime --transfers 16 --checkers 8 --bwlimit 10M --tpslimit 10 --log-level INFO --log-file /var/log/rclone-sync.log
            sleep 10
          done
      volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
        - name: rclone-config
          mountPath: /config
        - name: log-volume
          mountPath: /var/log
  livenessProbe:
    exec:
      command:
        - /bin/sh
        - -c
        - "curl -f http://localhost:8080/health || exit 1"
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

# Scheduler configuration
scheduler:
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
    - name: rclone-config
      mountPath: /config
    - name: log-volume
      mountPath: /var/log
  extraContainers:
    - name: rclone-sync
      image: kishoreel/rclone2-image:latest
      command:
        - /bin/bash
        - -c
        - |
          echo "Mount point for rclone config: /config/rclone.conf"
          while true; do
            echo "Running rclone sync..."
            rclone sync s3:airflow-dags-stage /opt/airflow/dags --config /config/rclone.conf --use-server-modtime --transfers 16 --checkers 8 --bwlimit 10M --tpslimit 10 --log-level INFO --log-file /var/log/rclone-sync.log
            sleep 10
          done
      volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
        - name: rclone-config
          mountPath: /config
        - name: log-volume
          mountPath: /var/log

# Webserver configuration
webserver:
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
    - name: rclone-config
      mountPath: /config
    - name: log-volume
      mountPath: /var/log
  extraContainers:
    - name: rclone-sync
      image: kishoreel/rclone2-image:latest
      command:
        - /bin/bash
        - -c
        - |
          echo "Mount point for rclone config: /config/rclone.conf"
          while true; do
            echo "Running rclone sync..."
            rclone sync s3:airflow-dags-stage /opt/airflow/dags --config /config/rclone.conf --use-server-modtime --transfers 16 --checkers 8 --bwlimit 10M --tpslimit 10 --log-level INFO --log-file /var/log/rclone-sync.log
            sleep 10
          done
      volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
        - name: rclone-config
          mountPath: /config
        - name: log-volume
          mountPath: /var/log
  service:
    type: ClusterIP  # Changed from LoadBalancer to ClusterIP
    ports:
      - name: http
        port: 80
        targetPort: 8080


# Triggerer configuration
triggerer:
  extraVolumes:
    - name: rclone-config
      configMap:
        name: rclone-config
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
    - name: rclone-config
      mountPath: /config
    - name: log-volume
      mountPath: /var/log
  extraContainers:
    - name: rclone-sync
      image: kishoreel/rclone2-image:latest
      command:
        - /bin/bash
        - -c
        - |
          echo "Mount point for rclone config: /config/rclone.conf"
          while true; do
            echo "Running rclone sync..."
            rclone sync s3:airflow-dags-stage /opt/airflow/dags --config /config/rclone.conf --use-server-modtime --transfers 16 --checkers 8 --bwlimit 10M --tpslimit 10 --log-level INFO --log-file /var/log/rclone-sync.log
            sleep 10
          done
      volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
        - name: rclone-config
          mountPath: /config
        - name: log-volume
          mountPath: /var/log

# DAG Processor configuration
dagProcessor:
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
    - name: rclone-config
      mountPath: /config
    - name: log-volume
      mountPath: /var/log
  extraContainers:
    - name: rclone-sync
      image: kishoreel/rclone2-image:latest
      command:
        - /bin/bash
        - -c
        - |
          echo "Mount point for rclone config: /config/rclone.conf"
          while true; do
            echo "Running rclone sync..."
            rclone sync s3:airflow-dags-stage /opt/airflow/dags --config /config/rclone.conf --use-server-modtime --transfers 16 --checkers 8 --bwlimit 10M --tpslimit 10 --log-level INFO --log-file /var/log/rclone-sync.log
            sleep 10
          done
      volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
        - name: rclone-config
          mountPath: /config
        - name: log-volume
          mountPath: /var/log
